export default {
  login: "divano9",
  id: 34340758,
  node_id: "MDQ6VXNlcjM0MzQwNzU4",
  avatar_url: "https://avatars.githubusercontent.com/u/34340758?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/divano9",
  html_url: "https://github.com/divano9",
  followers_url: "https://api.github.com/users/divano9/followers",
  following_url: "https://api.github.com/users/divano9/following{/other_user}",
  gists_url: "https://api.github.com/users/divano9/gists{/gist_id}",
  starred_url: "https://api.github.com/users/divano9/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/divano9/subscriptions",
  organizations_url: "https://api.github.com/users/divano9/orgs",
  repos_url: "https://api.github.com/users/divano9/repos",
  events_url: "https://api.github.com/users/divano9/events{/privacy}",
  received_events_url: "https://api.github.com/users/divano9/received_events",
  type: "User",
  site_admin: false,
  name: "Dušan Ivanović",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 19,
  public_gists: 5,
  followers: 30,
  following: 0,
  created_at: "2017-12-07T12:13:50Z",
  updated_at: "2023-05-24T12:22:51Z",
};
